on:
  push:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - run: crun --version

    - name: patch crun (Workaround for https://github.com/actions/runner-images/issues/9425)
      shell: bash
      run: |
        set -x
        curl -Lo ./crun https://github.com/containers/crun/releases/download/1.14.3/crun-1.14.3-linux-amd64
        GOOD_SHA=e217dfe816ed1af90f3ae923a84303e20b34f41bf68a236d9e506ba481b8d274
        sha256sum ./crun
        OUR_SHA=$(sha256sum ./crun | awk '{ print $1 }')
        if [[ "$GOOD_SHA" == "$OUR_SHA" ]]; then
            sudo install crun /usr/bin/crun
        else
            echo "Checksums do not match"
            exit 1
        fi

    - run: crun --version